version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - server
      - auditorium
      - vault
      - script

  server:
    build:
      context: '.'
      dockerfile: Dockerfile.golang
    working_dir: /offen/server
    volumes:
      - serverdata:/var/opt/offen
      - .:/offen
      - ./bootstrap.yml:/offen/server/bootstrap.yml
      - serverdeps:/data
    environment:
      GOPATH: /data/go
      OFFEN_APP_DEVELOPMENT: '1'
      OFFEN_SERVER_REVERSEPROXY: '1'
      OFFEN_SERVER_PORT: 8080
      OFFEN_SECRET: imLcp0dS4OaR6Lvl+z9tbg==
      OFFEN_APP_ROOTACCOUNT: 3c8e3495-17c5-4be3-836c-e56fc562ace0
    command: refresh run

  vault:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/vault
    environment:
      PORT: 9977
    volumes:
      - .:/offen
      - vaultdeps:/offen/vault/node_modules
    command: npm start

  script:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/script
    environment:
      PORT: 9966
    volumes:
      - .:/offen
      - scriptdeps:/offen/script/node_modules
    command: npm start

  auditorium:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/auditorium
    environment:
      PORT: 9955
    volumes:
      - .:/offen
      - auditoriumdeps:/offen/auditorium/node_modules
    command: npm start

  test_site:
    image: nginx:1.17-alpine
    ports:
      - 8081:80
    volumes:
      - ./test-site:/usr/share/nginx/html

volumes:
  serverdata:
  serverdeps:
  scriptdeps:
  auditoriumdeps:
  vaultdeps:
